Repository warengonzaga/gathertown.js, pull requests merged in 2021-11, with the labels that each got.

#1 🚀 RELEASE: v1.0.0-rc.1
  .github/funding.yml
  .gitignore
  CONTRIBUTING.md
  README.md
  dist/gather.js
  dist/gather.js.map
  package.json
  readme.md
  src/config.js
  src/index.js
  src/requester.js
  yarn.lock
Labels: in progress, maintainers-only, pre-release

#24 converted to typescript
  .editorconfig
  .eslintignore
  .eslintrc.json
  .gitignore
  .husky/.gitignore
  .husky/pre-commit
  .parcelrc
  .prettierignore
  .prettierrc.json
  dist/gather.js
  dist/gather.js.map
  dist/index.d.ts
  dist/index.d.ts.map
  package.json
  src/config.js
  src/config.ts
  src/index.js
  src/index.ts
  src/requester.js
  src/requester.ts
  tsconfig.json
  yarn.lock
Labels: in review, p2, tweak

#26 official landing page
  docs/assets/css/styles.css
  docs/assets/img/stars.png
  docs/assets/js/script.js
  docs/index.html
Labels: docs, p1, tweak

#16 🚀 RELEASE: v1.0.0-alpha.1
  .editorconfig
  .eslintignore
  .eslintrc.json
  .github/FUNDING.yml
  .github/img/repo_banner.png
  .gitignore
  .husky/.gitignore
  .husky/pre-commit
  .parcelrc
  .prettierignore
  .prettierrc.json
  CODE_OF_CONDUCT.md
  LICENSE
  README.md
  SECURITY.md
  dist/gather.js
  dist/gather.js.map
  dist/index.d.ts
  dist/index.d.ts.map
  docs/CNAME
  docs/assets/css/styles.css
  docs/assets/img/android-chrome-192x192.png
  docs/assets/img/android-chrome-512x512.png
  docs/assets/img/apple-touch-icon.png
  docs/assets/img/favicon-16x16.png
  docs/assets/img/favicon-32x32.png
  docs/assets/img/favicon.ico
  docs/assets/img/site.webmanifest
  docs/assets/img/stars.png
  docs/assets/js/script.js
  docs/index.html
  package.json
  security.md
  src/api/apiBase.ts
  src/api/createSpace.ts
  src/api/getEmailGuestList.ts
  src/api/getMap.ts
  src/api/setEmailGuestlist.ts
  src/api/setMap.ts
  src/api/validateStatus.ts
  src/config.js
  src/config.ts
  src/index.js
  src/index.ts
  src/requester.js
  src/types.ts
  tsconfig.json
  yarn.lock
Labels: in progress, maintainers-only, p1, release
